Select OPERATION_1.RESOURCE_ID As [Shop Resource2],
  OPERATION_1.WORKORDER_BASE_ID [WO Number],
  WORK_ORDER1.STATUS As [WO Status],
  WORK_ORDER1.PART_ID As [Part ID],
  WORK_ORDER1.DESIRED_RLS_DATE As [WO Release Date],
  WORK_ORDER1.DESIRED_WANT_DATE As [WO Want Date],
  Cast(OPERATION_1.CALC_END_QTY As Int) As [WO QTY],
  PART.DESCRIPTION As [Part Description],
  Case
    When WORKORDER_BINARY.TYPE = 'D' Then IsNull(Cast(Cast(WORKORDER_BINARY.BITS
    As VarBinary(Max)) As nvarchar(max)), '') Else '' End As [WO Specs]
From OPERATION As OPERATION_1
  Inner Join (Select WORK_ORDER.TYPE,
    WORK_ORDER.BASE_ID,
    WORK_ORDER.LOT_ID,
    WORK_ORDER.SPLIT_ID,
    WORK_ORDER.SUB_ID,
    WORK_ORDER.GLOBAL_RANK,
    WORK_ORDER.STATUS,
    WORK_ORDER.DESIRED_WANT_DATE,
    WORK_ORDER.SCHED_FINISH_DATE,
    Case When CO_PRODUCT.DESIRED_QTY Is Null Then WORK_ORDER.DESIRED_QTY
      Else CO_PRODUCT.DESIRED_QTY End As DESIRED_QTY,
    WORK_ORDER.DESIRED_RLS_DATE,
    Case When CO_PRODUCT.PART_ID Is Null Then WORK_ORDER.PART_ID
      Else CO_PRODUCT.PART_ID End As PART_ID,
    WORK_ORDER.CREATE_DATE
  From WORK_ORDER
    Left Outer Join CO_PRODUCT On WORK_ORDER.TYPE = CO_PRODUCT.WORKORDER_TYPE
      And WORK_ORDER.BASE_ID = CO_PRODUCT.WORKORDER_BASE_ID And
      WORK_ORDER.LOT_ID = CO_PRODUCT.WORKORDER_LOT_ID And WORK_ORDER.SPLIT_ID =
      CO_PRODUCT.WORKORDER_SPLIT_ID And
      WORK_ORDER.SUB_ID = CO_PRODUCT.WORKORDER_SUB_ID) As WORK_ORDER1
    On OPERATION_1.WORKORDER_TYPE = WORK_ORDER1.TYPE And
    OPERATION_1.WORKORDER_BASE_ID = WORK_ORDER1.BASE_ID And
    OPERATION_1.WORKORDER_LOT_ID = WORK_ORDER1.LOT_ID And
    OPERATION_1.WORKORDER_SPLIT_ID = WORK_ORDER1.SPLIT_ID And
    OPERATION_1.WORKORDER_SUB_ID = WORK_ORDER1.SUB_ID
  Left Outer Join PART On WORK_ORDER1.PART_ID = PART.ID
  Full Outer Join WORKORDER_BINARY
    On WORK_ORDER1.TYPE = WORKORDER_BINARY.WORKORDER_TYPE And
    WORK_ORDER1.BASE_ID = WORKORDER_BINARY.WORKORDER_BASE_ID And
    WORK_ORDER1.LOT_ID = WORKORDER_BINARY.WORKORDER_LOT_ID And
    WORK_ORDER1.SPLIT_ID = WORKORDER_BINARY.WORKORDER_SPLIT_ID And
    WORK_ORDER1.SUB_ID = WORKORDER_BINARY.WORKORDER_SUB_ID
Where OPERATION_1.RESOURCE_ID = 'AWC-DRV-PRGM ' And WORK_ORDER1.STATUS = 'R'
