------database interactive



SELECT TB1.WORKORDER_TYPE,TB1.WORKORDER_BASE_ID,TB1.WORKORDER_LOT_ID,TB1.WORKORDER_SUB_ID,TB2.CALC_START_QTY AS [WO QTY],TB1.PART_ID,TB1.CALC_QTY AS [PART QTY] FROM

(select WORKORDER_TYPE,WORKORDER_BASE_ID,WORKORDER_LOT_ID,WORKORDER_SPLIT_ID,WORKORDER_SUB_ID,PART_ID,CALC_QTY from REQUIREMENT  where PART_ID='HAR0213' AND WORKORDER_TYPE='W') AS TB1
LEFT OUTER JOIN
(SELECT WORKORDER_TYPE,WORKORDER_BASE_ID,WORKORDER_LOT_ID,WORKORDER_SPLIT_ID,WORKORDER_SUB_ID,CALC_START_QTY FROM OPERATION WHERE WORKORDER_LOT_ID='1' AND WORKORDER_SUB_ID='0') AS TB2
ON TB1.WORKORDER_BASE_ID=TB2.WORKORDER_BASE_ID
WHERE TB2.CALC_START_QTY >=100 OR TB1.CALC_QTY>=5
